// Chapter 26: Rounding Numbers

// Rounding a number to the nearest integer
let number = 4.56;
let roundedNumber = Math.round(number);
console.log(`Rounded to nearest integer: ${roundedNumber}`);

// Rounding up a number represented by origNum and assign it to roundNum
let origNum1 = 4.2;
let roundNum1 = Math.ceil(origNum1);
console.log(`Rounded up: ${roundNum1}`);

// Rounding down a number represented by origNum and assign it to roundNum
let origNum2 = 4.9;
let roundNum2 = Math.floor(origNum2);
console.log(`Rounded down: ${roundNum2}`);

// Rounding a number represented by a variable and assign the result to a second variable
let origNum3 = 4.56;
let roundedNum = Math.round(origNum3);
console.log(`Rounded number: ${roundedNum}`);

// Rounding 0.5 to 0 and assign it to a variable
let roundedZero = Math.round(0.5);
console.log(`Rounded 0.5 to: ${roundedZero}`);

// Chapter 27: Random Numbers

// Convert a random number generated by JavaScript to a number in the range 1 to 50
let randomNum1 = Math.floor(Math.random() * 50) + 1;
console.log(`Random number in range 1 to 50: ${randomNum1}`);

// Generate a random number and assign it to a variable
let randomNum2 = Math.random();
console.log(`Random number: ${randomNum2}`);

// Creating a dice with pseudo-random number
let diceRoll = Math.floor(Math.random() * 6) + 1;
console.log(`Dice roll: ${diceRoll}`);

// Creating a coin toss with pseudo-random number
let coinToss = Math.random() < 0.5 ? 'Heads' : 'Tails';
console.log(`Coin toss: ${coinToss}`);

// Chapter 28 & 29: Converting Strings

// Convert a string to an integer in JavaScript
let strToInt = parseInt("123");
console.log(`String to integer: ${strToInt}`);

// Convert the string "123" to an integer
let strNum = "123";
let intNum = parseInt(strNum);
console.log(`Converted string "123" to integer: ${intNum}`);

// Convert a string containing a decimal number to a floating-point number
let strDecimal = "3.14";
let floatNum = parseFloat(strDecimal);
console.log(`Converted string "3.14" to float: ${floatNum}`);

// Check if a string can be converted to an integer or decimal before conversion
let str1 = "123";
let str2 = "3.14";
let str3 = "abc";
let isInt = !isNaN(parseInt(str1));
let isFloat = !isNaN(parseFloat(str2));
let invalidStr = isNaN(parseInt(str3)) && isNaN(parseFloat(str3));
console.log(`String "123" is integer: ${isInt}`);
console.log(`String "3.14" is float: ${isFloat}`);
console.log(`String "abc" is invalid: ${invalidStr}`);

// Convert a number to a string in JavaScript
let numToStr = number.toString();
console.log(`Converted number to string: ${numToStr}`);

// Convert the number 42 to a string
let num42 = 42;
let str42 = num42.toString();
console.log(`Converted number 42 to string: ${str42}`);

// Convert a string representing a decimal number to an integer
let decimalStr = "3.14";
let decimalInt = parseInt(decimalStr);
console.log(`Converted decimal string "3.14" to integer: ${decimalInt}`);

// Chapter 30: Controlling the length of decimals

// Rounding a number to 4 decimal places and converting it to a string
let num = 5.123456789;
let roundedTo4Places = num.toFixed(4).toString();
console.log(`Rounded to 4 decimal places and converted to string: ${roundedTo4Places}`);

// Rounding a number to 2 decimal places, converting it to a string, converting it back to a number
num = num.toFixed(2);
num = parseFloat(num);
console.log(`Rounded to 2 decimal places and back to number: ${num}`);

// Testing if a number rounded to 2 digits and converted to a string has more than 4 characters
let testNum = 5.123456789;
let roundedTo2Digits = testNum.toFixed(2).toString();
if (roundedTo2Digits.length > 4) {
    console.log(`The rounded number has more than 4 characters: ${roundedTo2Digits}`);
} else {
    console.log(`The rounded number does not have more than 4 characters: ${roundedTo2Digits}`);
}

// Assigning a number with many decimal places to a variable
let longDecimalNum = 9.87654321;
let roundedTo2DecimalPlaces = longDecimalNum.toFixed(2).toString();
alert(`Number rounded to 2 decimal places and converted to string: ${roundedTo2DecimalPlaces}`);

//  Math

// // Function to display a message in the browser
function displayMessage(message) {
    document.write(message + "<br>");
}

// Function to simulate a dice roll using Math.random()
function rollDice() {
    return Math.floor(Math.random() * 6) + 1;
}

// Function to simulate a coin toss using Math.random()
function tossCoin() {
    return Math.random() < 0.5 ? "Heads" : "Tails";
}

// 1. Takes a positive integer from the user and displays round off, floor, and ceil values
let posNum = parseInt(prompt("Enter a positive integer:"));
displayMessage(`Number: ${posNum}`);
displayMessage(`Round off value: ${Math.round(posNum)}`);
displayMessage(`Floor value: ${Math.floor(posNum)}`);
displayMessage(`Ceil value: ${Math.ceil(posNum)}`);

// 2. Takes a negative floating point number from the user and displays round off, floor, and ceil values
let negFloat = parseFloat(prompt("Enter a negative floating-point number:"));
displayMessage(`Number: ${negFloat}`);
displayMessage(`Round off value: ${Math.round(negFloat)}`);
displayMessage(`Floor value: ${Math.floor(negFloat)}`);
displayMessage(`Ceil value: ${Math.ceil(negFloat)}`);

// 3. Displays the absolute value of a number
let absNum = parseFloat(prompt("Enter a number to find its absolute value:"));
displayMessage(`Absolute value of ${absNum}: ${Math.abs(absNum)}`);

// 4. Simulates a dice roll using random() method and displays the value
let diceValue = rollDice();
displayMessage(`Dice roll value: ${diceValue}`);

// 5. Simulates a coin toss using random() method and displays the result
let coinResult = tossCoin();
displayMessage(`Coin toss result: ${coinResult}`);

// 6. Shows a random number between 1 and 100 in the browser
let randomNum = Math.floor(Math.random() * 100) + 1;
displayMessage(`Random number between 1 and 100: ${randomNum}`);

// 7. Takes user's weight input and displays it
let userWeight = prompt("Enter your weight (e.g., 50, 50kgs, 50.2kgs, 50.2kilograms):");
let parsedWeight = parseFloat(userWeight);
displayMessage(`Your weight is: ${parsedWeight} kg`);

// 8. Stores a random secret number from 1 to 10 and asks the user to guess the number
let secretNum = Math.floor(Math.random() * 10) + 1;
let userGuess = parseInt(prompt("Guess a number between 1 and 10:"));
if (userGuess === secretNum) {
    displayMessage("Congratulations! You guessed the correct number.");
} else {
    displayMessage(`Sorry, the correct number was ${secretNum}. Better luck next time!`);
}
